### ISSUE TITLE
Allow for LDAP server pool configuration instead of a single LDAP server

### ISSUE THREAD

**Issue by nsballmann** [devpi/devpi-ldap#50]
In the current configuration there is a single `url:` value with which a single LDAP server can be configured. For small setups this may be sufficient.

In bigger setups (in our case an AD) there are redundant LDAP servers (in our case multiple AD Controllers (ADCs) around the world with different latencies) available, to not have downtime in dependent applications (like devpi-server with devpi-ldap) while one of those ADCs is having its maintenance window (with downtime).

To my understanding at the moment I need to change the value for `url:` in `ldap.yaml` to switch to a different ADC/LDAP server in case my primarily configured server goes down or has maintenance.

In other applications there is the possibility to configure a *Pool* of LDAP servers with multiple URLs to avoid this problem. They keep a known-good list and query the first server in that list. If that server goes down it's taken off the list and the next one in the pool will be queried. It will be reintegrated into the list by different means, some add it to the list after some time, others check regularly the availability of the pools server and order them by response time.

To my understanding `ldap3` is used for the LDAP connections and this package has the needed feature already [built-in](https://ldap3.readthedocs.io/en/latest/server.html?highlight=Pool#server-pool).

So please allow for configuration of multiple LDAP servers as a pool.

For backwards compatibility a single server configuration can be created as pool with a single server in it.

Sadly I don't have a configuration available which covers all the edge cases, but i think something like this can be made work:

```yaml
---
devpi-ldap:
  pool:
    - url: ldaps://server1.example.com:636
      tls:
        validate: 2 # ssl.CERT_REQUIRED
        ca_certs_file: /etc/ssl/certs/ca-certificates.crt
    - url: ldap://server2.example.com:389
    - url: ldaps://server3.example.com:3269
      tls:
        validate: 2 # ssl.CERT_REQUIRED
        ca_certs_file: /etc/ssl/certs/ca-certificates.crt
    - url: ldap://server4.example.com:3268
  user_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=user)(sAMAccountName={username}))
    attribute_name: distinguishedName
  group_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=group)(member={userdn}))
    attribute_name: CN
```

**Comment by fschulze** [comment]
As this is an enterprise requirement I will either gladly accept a PR which implements this or you can contact mail@pyfidelity.com for a quote to implement it.

**Comment by nsballmann** [comment]
For backwards compatibility of the configuration this

```yaml
---
devpi-ldap:
  url: ldaps://example.com:3269
  tls:
    validate: 2 # ssl.CERT_REQUIRED
    ca_certs_file: /etc/ssl/certs/ca-certificates.crt
  user_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=user)(sAMAccountName={username}))
    attribute_name: distinguishedName
  group_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=group)(member={userdn}))
    attribute_name: CN
```

can be mapped to this:

```yaml
---
devpi-ldap:
  pool:
    - url: ldaps://example.com:3269
      tls:
        validate: 2 # ssl.CERT_REQUIRED
        ca_certs_file: /etc/ssl/certs/ca-certificates.crt
  user_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=user)(sAMAccountName={username}))
    attribute_name: distinguishedName
  group_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=group)(member={userdn}))
    attribute_name: CN
```
