### ISSUE TITLE
[Feature Request] Trigger config/password reload (or periodically reload)

### ISSUE THREAD

**Issue by con-f-use** [devpi/devpi-ldap#56]
We rotate passwords for our LDAP service users. It would be nice, if at least the password, if not the whole ldap config could be reloaded without restarting the whole service. The reload might either be triggered (e.g. sending the HUP-signal, or any other signal, to the devpi server) or simply done periodically.

**Comment by fschulze** [comment]
I don't understand how rotating passwords is a problem. Each login re-validates the password via LDAP which creates a token that is valid for 10 hours.

Rotating passwords is an old recommendation that turned out to be a bad idea in regard to password security, as it causes users to choose simple passwords with only slight predictable changes.

Reloading the config could be possible, but I don't see a use case for that, as the configuration should be pretty static most of the time. Could you elaborate on why you would need that?

**Comment by con-f-use** [comment]
The rotation for service user accounts is done automatically and chooses sufficiently complex and random passwords.

**Comment by fschulze** [comment]
That is fine then. I still don't understand what the problem on the devpi-server side is then. The passwords are in LDAP and are validated each time. There is no caching or anything like that.

**Comment by con-f-use** [comment]
Yeah sorry, that key piece of info stayed in my head, but that's not a place for the outside world :grin:

**Comment by fschulze** [comment]
I have to think about that. It would be better if that wasn't in the config at all. How do you solve that for other services? Would using the ``keyring`` package work for you? Or should the password be read from another file or from the environment? I'm not too deep into that stuff, but passwords in configuration generally bother me and I haven't seen a good general solution yet. There are some "vault" thingies, but they seem to be too complex for simple use cases.

**Comment by con-f-use** [comment]
You're right, it should not be in the config, because you want to commit config without committing secrets. The `keyring` package, on the other hand, can be a pain to use in some applications. I'm most happy when it's just a configurable file path.

So my vote would be to introduce a new `password_file` keyword:
```
---
devpi-ldap:
  url: ldaps://ldap.cuda-inc.com:636
  user_search:
    userdn: SERVICE-LDAP@ad.myorg.com
    password_file: /some/arbitrary/path/to/a/password.txt  <---- this
    base: DC=EU,DC=AD,DC=MYORG,DC=COM
    filter: (&(objectClass=user)(userPrincipalName={username}))
    attribute_name: distinguishedName
 ```
 
 and then, if you wanted to be extra accommodating have a correspoding environment variable and command-line option.
