### ISSUE TITLE
Invalid default configuration

### ISSUE THREAD

**Issue by StephanErb** [devpi/devpi-ldap#6]
The configuration example provided in the README.md is invalid according to the `devlpi-ldap` verification script. This is not a real problem, but more an unnecessary inconvenience. 

``` yaml
devpi-ldap:
  url: ldap://example.com
  user_template: CN={username},CN=Partition1,DC=Example,DC=COM
  user_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=user)(sAMAccountName={username}))
    attribute_name: distinguishedName
  group_search:
    base: CN=Partition1,DC=Example,DC=COM
    filter: (&(objectClass=group)(member={userdn}))
    attribute_name: CN

```

``` bash
 $ devpi-ldap  ldap.yml 
2014-10-27 11:34:22,627 ERROR NOCTX The LDAP options 'user_template' and 'user_search' are mutually exclusive.
```
